name: Java CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testdb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u user -ppassword"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Wait for MySQL to be ready
        run: |
          until mysqladmin ping -h localhost -u user -p password --silent; do
            echo "Waiting for MySQL..."
            sleep 5
          done

      - name: Set up environment variables
        env:
          SPRING_DATASOURCE_URL: "jdbc:mysql://localhost:3306/testdb"
          SPRING_DATASOURCE_USERNAME: "user"
          SPRING_DATASOURCE_PASSWORD: "password"
        run: echo "Environment variables set."

      - name: Build with Maven (skip tests)
        run: mvn -B package -DskipTests
